#!/bin/bash
SCRIPT_DIR="$(dirname $0)"
# For production, create `application.properties` in `config` subfolder
java -cp /usr/share/java/opencv.jar:$SCRIPT_DIR'/target/dependency/*:'$SCRIPT_DIR'/target/classes' org.soluvas.scrape.core.cli.MultiScrapeThenSummarize
